### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by wa1kb0y** [cedx/yii2-mustache#4]
Just trying to install 😞 
php7.0
![2018-02-08_03-29-55](https://user-images.githubusercontent.com/5966172/35940046-80d34680-0c80-11e8-87a8-4da5ec14d23e.jpg)

**Comment by cedx** [comment]
You're probably using the version 9.0.0... which requires PHP 7.1.
Downgrade to version 8.0.0, and everything should be OK.

**Comment by wa1kb0y** [comment]
Yes, u are right, changed composer.json to `"cedx/yii2-mustache": "~8.0"` and now it works. Thank you!
