### ISSUE TITLE
Render string templates

### ISSUE THREAD

**Issue by wa1kb0y** [cedx/yii2-mustache#5]
Is there any way to use this with templates stored in database? 
Something like:
```php
$t = Template::find()->where(['something'=>1])->one();
return $this->render(['view'=>$t->body, 'ext'=>'mustache'], ['param1'=>'test']);
```
Could you add such feature?

**Comment by cedx** [comment]
I don't think so as rendering is largely managed by the framework, not by extensions. There's already some open issues related to the rendering of a string in the [Yii2 repo](https://github.com/yiisoft/yii2):

- https://github.com/yiisoft/yii2/issues/7309
- https://github.com/yiisoft/yii2/pull/15116

A solution could be to render manually your string with the [Mustache engine](https://github.com/bobthecow/mustache.php), and inject it back into your layout using the [`renderContent()`](http://www.yiiframework.com/doc-2.0/yii-base-controller.html#renderContent()-detail) method in your controller.

Something like (not tested!):

```php
$view = Template::find()->where(['something' => 1])->one()->body;
$content = (new \Mustache_Engine)->render($view, ['param1' => 'test']);
return $this->renderContent($content);
```

(You should not need to update your `composer.json` file for using the `\Mustache_Engine` class, as the Mustache library is already imported by the Yii extension)

**Comment by wa1kb0y** [comment]
It works, thank you a lot!
Also maybe good idea to override render() method like in this advice https://github.com/yiisoft/yii2/issues/6252#issuecomment-240141112
